// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ddmrp.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Footer")]
    [NUnit.Framework.CategoryAttribute("Footer")]
    public partial class FooterFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Footer.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Footer", "\tIn order to navigate to other links from the footer\r\n\tAs a user on the site\r\n\tI " +
                    "want to be able to navigate to various links from the footer", ProgrammingLanguage.CSharp, new string[] {
                        "Footer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Success footer link")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("Success")]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "Locale", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "SiteMap", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "ContactUs", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "Privacy", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "Terms", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "Trademarks", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        [NUnit.Framework.TestCaseAttribute("Bottom Footer", "AboutAds", "https://www.microsoft.com/en-us/surface/devices/surface-book-2/overview", null)]
        public virtual void SuccessFooterLink(string section, string link, string url, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UI",
                    "Success"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Success footer link", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on HomePage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When(string.Format("I click on a link {0} from footer", link), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("the corresponding web page {0} should render", link), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
